2024-01-14 12:45:18,499 - INFO - Step 1: Downloaded 7274 tickers from NASDAQ.
2024-01-14 12:45:18,536 - INFO - Step 2: 3971 tickers passed through the filter.
2024-01-14 12:45:18,544 - INFO - Step 3: 0 new rows inserted into Tickers file.
2024-01-14 12:45:18,552 - INFO - Step 4: All tickers are up to date.
2024-01-14 12:55:00,894 - INFO - Step 1: Downloaded 7274 tickers from NASDAQ.
2024-01-14 12:55:00,931 - INFO - Step 2: 3971 tickers passed through the filter.
2024-01-14 12:55:00,939 - INFO - Step 3: 0 new rows inserted into Tickers file.
2024-01-14 12:55:00,947 - INFO - Step 4: All tickers are up to date.
2024-01-15 11:27:43,350 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 115, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 165, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 11:27:43,355 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 125, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 11:27:43,355 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 136, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 11:27:43,376 - INFO - Step 4: All tickers are up to date.
2024-01-15 11:29:05,980 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'CVS', 'CVX', 'D', 'DD', 'DE', 'DHR', 'DINO', 'DIS', 'DOV', 'DTE', 'DUK', 'DVN', 'EA', 'ECL', 'ED', 'EFX', 'EIX', 'EMR', 'ENB', 'EOG', 'EQT', 'ES', 'ETN', 'ETR', 'EVRG', 'EXC', 'EXPD'] is successfully downloaded.
2024-01-15 11:29:08,980 - INFO - Download complete.
2024-01-15 14:03:34,228 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 14:03:34,232 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 14:03:34,232 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 14:03:34,249 - INFO - Step 4: All tickers are up to date.
2024-01-15 14:04:34,111 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'F', 'FAST', 'FDX', 'FHN', 'FI', 'FICO', 'FITB', 'FL', 'FMC', 'GD', 'GE', 'GIS', 'GLW', 'GOLD', 'GPC', 'GPS', 'GWW', 'HAL', 'HBAN', 'HD', 'HES', 'HON', 'HPQ', 'HRL', 'HST'] is successfully downloaded.
2024-01-15 14:05:36,550 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'HSY', 'HUBB', 'HUM', 'IBM', 'IEX', 'IFF', 'IMGN', 'INTC', 'IP', 'IPG', 'ITW', 'JBHT', 'JCI', 'JNJ', 'JPM', 'K', 'KEY', 'KLAC', 'KMB', 'KO', 'KR', 'LEN', 'LHX', 'LLY', 'LMT'] is successfully downloaded.
2024-01-15 14:06:36,181 - ERROR - 
1 Failed download:
2024-01-15 14:06:36,182 - ERROR - ['MKC']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:09:53,798 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 15:09:53,802 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 15:09:53,803 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 15:09:53,832 - INFO - Step 4: All tickers are up to date.
2024-01-15 15:10:53,471 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN', 'LOW', 'LRCX', 'LSCC', 'LUV', 'MAS', 'MCD', 'MDT', 'MGM', 'MKC', 'MMC', 'MMM', 'MNST', 'MO', 'MOS', 'MRK', 'MRO', 'MSFT', 'MSI', 'MTB', 'MU', 'NEE', 'NEM', 'NI', 'NKE'] is successfully downloaded.
2024-01-15 15:11:55,863 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN', 'NOC', 'NSC', 'NTRS', 'NUE', 'NVO', 'OKE', 'OMC', 'ORCL', 'OXY', 'PAYX', 'PCAR', 'PCG', 'PEAK', 'PEG', 'PEP', 'PFE', 'PG', 'PGR', 'PH', 'PHM', 'PNC', 'PPG', 'PPL', 'PSA'] is successfully downloaded.
2024-01-15 15:12:55,614 - ERROR - 
1 Failed download:
2024-01-15 15:12:55,614 - ERROR - ['TJX']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:12:56,741 - ERROR - refactor_dataframe_columns() - df.astype(), Error: "Only a column name can be used for the key in a dtype mappings argument. 'splits' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 259, in refactor_dataframe_columns
    df = df.astype(new_cols_types)
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'splits' not found in columns."
2024-01-15 15:28:02,496 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 15:28:02,501 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 15:28:02,501 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 15:28:02,531 - INFO - Step 4: All tickers are up to date.
2024-01-15 15:29:02,205 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN', 'PTC', 'RF', 'RGEN', 'ROK', 'ROST', 'RTX', 'SCHW', 'SHW', 'SLB', 'SO', 'SPGI', 'STT', 'SU', 'SWK', 'SWKS', 'SWN', 'SYK', 'SYY', 'T', 'TER', 'TFC', 'TGT', 'TJX', 'TMO'] is successfully downloaded.
2024-01-15 15:30:04,713 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN', 'TOL', 'TROW', 'TRV', 'TSN', 'TT', 'TXN', 'UDR', 'UL', 'UNH', 'UNP', 'USB', 'VFC', 'VLO', 'VMC', 'VZ', 'WBA', 'WDC', 'WEC', 'WELL', 'WFC', 'WHR', 'WM', 'WMB', 'WMT'] is successfully downloaded.
2024-01-15 15:30:30,507 - ERROR - 
1 Failed download:
2024-01-15 15:30:30,507 - ERROR - ['ETR']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:37:13,513 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 15:37:13,519 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 15:37:13,519 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 15:37:13,541 - INFO - Step 4: All tickers are up to date.
2024-01-15 15:37:36,706 - ERROR - 
1 Failed download:
2024-01-15 15:37:36,706 - ERROR - ['ETR']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:37:36,982 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:41:55,714 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 15:41:55,717 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 15:41:55,717 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 15:41:55,740 - INFO - Step 4: All tickers are up to date.
2024-01-15 15:42:20,753 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN', 'WSM', 'WSO', 'WST', 'WY', 'XEL', 'XOM', 'XRAY'] is successfully downloaded.
2024-01-15 15:42:34,348 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN'] is successfully downloaded.
2024-01-15 15:42:45,813 - ERROR - 
1 Failed download:
2024-01-15 15:42:45,813 - ERROR - ['CRH']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:42:45,910 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:42:45,932 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'CRH', 'ES', 'ETR', 'IMGN'] is successfully downloaded.
2024-01-15 15:42:57,696 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'ES', 'ETR', 'IMGN'] is successfully downloaded.
2024-01-15 15:43:09,426 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'ES', 'ETR', 'IMGN'] is successfully downloaded.
2024-01-15 15:43:21,401 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'ES', 'ETR', 'IMGN'] is successfully downloaded.
2024-01-15 15:43:29,113 - ERROR - 
2 Failed downloads:
2024-01-15 15:43:29,113 - ERROR - ['ETR', 'CMS']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:43:29,160 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:43:29,164 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:43:29,181 - INFO - Quotes files of the batch of tickers ['AEM', 'CMS', 'ES', 'ETR', 'IMGN'] is successfully downloaded.
2024-01-15 15:43:37,757 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:43:45,230 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:43:52,848 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:44:00,599 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:44:08,356 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:44:15,981 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:44:23,426 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:44:31,090 - INFO - Quotes files of the batch of tickers ['AEM', 'ES', 'IMGN'] is successfully downloaded.
2024-01-15 15:47:27,460 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 15:47:27,464 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 15:47:27,464 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 15:47:27,488 - INFO - Step 4: All tickers are up to date.
2024-01-15 15:50:30,679 - ERROR - Step 1 failed: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 116, in run
    nasdaq_tickers = self.download_tickers_from_nasdaq()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 173, in download_tickers_from_nasdaq
    return pd.DataFrame(data['rows'], columns=data['headers'])
                        ~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-01-15 15:50:30,682 - ERROR - Step 2 failed: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 132, in run
    clean_tickers = self.preprocess_downloaded_data(nasdaq_tickers)
                                                    ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'nasdaq_tickers' where it is not associated with a value
2024-01-15 15:50:30,683 - ERROR - Step 3 failed: cannot access local variable 'clean_tickers' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/tickers_downloader.py", line 143, in run
    new_rows = self.add_new_data_to_file(clean_tickers)
                                         ^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'clean_tickers' where it is not associated with a value
2024-01-15 15:50:30,704 - INFO - Step 4: All tickers are up to date.
2024-01-15 15:50:35,264 - ERROR - Failed to get ticker 'BF-B' reason: bad parameter or other API misuse
2024-01-15 15:51:29,821 - ERROR - 
2 Failed downloads:
2024-01-15 15:51:29,822 - ERROR - ['BF-B']: Exception('%ticker%: No timezone found, symbol may be delisted')
2024-01-15 15:51:29,822 - ERROR - ['COO']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:51:30,460 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:51:30,621 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:51:30,799 - INFO - Quotes files of the batch of tickers ['AEM', 'AOS', 'ARW', 'AVY', 'BC', 'BCE', 'BEN', 'BF-B', 'BIO', 'BN', 'BXMT', 'CAR', 'CASY', 'CGNX', 'CINF', 'CLH', 'CMA', 'CMC', 'COHR', 'COO', 'CSL', 'DXC', 'EGP', 'ERIC', 'ES', 'FCNCA', 'FRT', 'GEN', 'GFI', 'GGG'] is successfully downloaded.
2024-01-15 15:52:33,044 - INFO - Quotes files of the batch of tickers ['CLH', 'EGP', 'FCNCA', 'GL', 'HAS', 'HEI', 'HRB', 'IMGN', 'JKHY', 'JWN', 'KBH', 'KGC', 'L', 'LNC', 'LNT', 'LNW', 'MAT', 'MGA', 'MIDD', 'MKL', 'MTH', 'MTZ', 'MUR', 'NNN', 'NYT', 'OGE', 'OLN', 'OSK', 'PII', 'PNR'] is successfully downloaded.
2024-01-15 15:53:35,129 - INFO - Quotes files of the batch of tickers ['CLH', 'EGP', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW', 'PVH', 'RHI', 'RJF', 'ROL', 'RPM', 'RRC', 'RRX', 'RVTY', 'SCI', 'SEE', 'SIG', 'SNA', 'SONY', 'SPB', 'TAP', 'TDW', 'TECH', 'TEVA', 'TFX', 'THC', 'THO', 'TM'] is successfully downloaded.
2024-01-15 15:54:25,205 - INFO - Quotes files of the batch of tickers ['CLH', 'EGP', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW', 'THC', 'TPL', 'TRP', 'TTC', 'TXT', 'TYL', 'UHS', 'UNM', 'VNO', 'VOD', 'VTRS', 'WBS', 'WEN', 'WRB', 'WTRG', 'ZION'] is successfully downloaded.
2024-01-15 15:54:42,843 - ERROR - 
1 Failed download:
2024-01-15 15:54:42,843 - ERROR - ['EGP']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:54:42,995 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:54:43,025 - INFO - Quotes files of the batch of tickers ['CLH', 'EGP', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW', 'THC'] is successfully downloaded.
2024-01-15 15:54:58,575 - ERROR - 
1 Failed download:
2024-01-15 15:54:58,576 - ERROR - ['THC']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:54:58,723 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:54:58,738 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW', 'THC'] is successfully downloaded.
2024-01-15 15:55:14,222 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:55:29,835 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:55:45,361 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:55:59,086 - ERROR - 
1 Failed download:
2024-01-15 15:55:59,086 - ERROR - ['MTH']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:55:59,221 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:55:59,240 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'MTH', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:56:13,005 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:56:26,628 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:56:38,145 - ERROR - 
1 Failed download:
2024-01-15 15:56:38,145 - ERROR - ['FCNCA']: InterfaceError('bad parameter or other API misuse')
2024-01-15 15:56:38,254 - ERROR - refactor_dataframe_columns(). Error: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
Traceback (most recent call last):
  File "/Users/roman/PycharmProjects/quotes_downloader/quotes_downloader.py", line 252, in refactor_dataframe_columns
    df = df.astype(self.COLS_TYPES)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/roman/PycharmProjects/quotes_downloader/venv/lib/python3.12/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'dividends' not found in columns."
2024-01-15 15:56:38,278 - INFO - Quotes files of the batch of tickers ['CLH', 'FCNCA', 'IMGN', 'MKL', 'NNN', 'PNW'] is successfully downloaded.
2024-01-15 15:56:50,051 - INFO - Quotes files of the batch of tickers ['CLH', 'IMGN', 'MKL', 'NNN', 'PNW'] is successfully downloaded.
